export const CONFIG = {
  title: "Reign of Fire",
  worldSize: 280,
  terrainSegments: 128,
  player: {
    eye: 1.72,
    speed: 7.4,
    sprint: 12.2,
    crouch: 3.6,
    accel: 38,
    gravity: 22,
    jump: 8.5,
    mouse: 0.0018,
    radius: 0.42,
  },
  weapon: {
    bolts: 8,
    muzzle: 92,
    gravity: 9.2,
    reload: 2.15,
    recoil: 0.034,
    cooldown: 0.62,
    mass: 0.42,
    damage: 85,
  },
  hunt: {
    // Difficulty ramps by aggression and armour, not just by hit points.
    flights: [
      { label: "Scavengers on the slope", species: ["emberkin", "emberkin"] },
      { label: "Forge-hot harrier", species: ["cinderwyrm"] },
      { label: "The ridge's landlord", species: ["ashwrought"] },
      { label: "They hunt in threes", species: ["rustwing", "rustwing", "rustwing"] },
      { label: "Fumarole brood", species: ["sulfurmaw", "emberkin"] },
      { label: "Something is stalking you", species: ["pale_stalker"] },
      { label: "Walking siege", species: ["basalt_tyrant", "cinderwyrm"] },
    ],
    flightGap: 6,
    corpseLinger: 9,
    mortarRadius: 9,
    cloudLife: 7,
    cloudRadius: 7,
  },
  quality: {
    targetFps: 60,
    particleAsh: 900,
    particleEmber: 220,
    // Fraction of native resolution each tier rasterises at.
    renderScale: { low: 0.55, medium: 0.78, high: 1, cinematic: 1 },
  },
};
