/**
 * Dragon species roster.
 *
 * Each entry drives three things at once:
 *  - `build`   : procedural anatomy (proportions, horns, spikes, wing shape)
 *  - `look`    : material pack + emissive/eye grading
 *  - `mind`    : personality weights the AI reads every frame
 *
 * `mind.aggression` is the master dial (0 = skittish scavenger, 1 = suicidal
 * berserker). It scales engage range, attack cadence, and how much damage the
 * beast will eat before it breaks off.
 */

export const ATTACK = {
  DIVE_FIRE: "dive_fire",
  STRAFE_RUN: "strafe_run",
  HOVER_BARRAGE: "hover_barrage",
  LAVA_MORTAR: "lava_mortar",
  AMBUSH_LUNGE: "ambush_lunge",
  VENOM_SPRAY: "venom_spray",
  TAIL_SWEEP: "tail_sweep",
};

export const SPECIES = {
  ashwrought: {
    id: "ashwrought",
    name: "Ashwrought",
    epithet: "Obsidian Tyrant",
    tier: 2,
    bounty: 400,
    codex:
      "The ridge's landlord. Holds a circling patrol until you enter its cone, then commits to long dive-fire runs and refuses to break off until badly wounded.",
    build: {
      scale: 8.2,
      neck: 1.0,
      tailSegments: 5,
      horns: 2,
      hornLength: 0.7,
      spikes: true,
      wingSpan: 1.0,
      bodyGirth: 1.0,
      headSize: 1.0,
    },
    look: {
      pack: "dragon_scales",
      scaleRepeat: [3.5, 2.2],
      emissive: [1.15, 0.18, 0.03],
      emissiveBase: 0.45,
      eye: 0xff2a00,
      glow: 0xff4a12,
      glowIntensity: 18,
      metalness: 0.22,
      roughness: 0.42,
      wingTint: 0xffffff,
    },
    stats: {
      hp: 1100,
      flySpeed: 22,
      diveSpeed: 38,
      turnRate: 3.4,
      patrolRadius: 22,
      patrolHeight: 36,
      spotRange: 140,
      attackRange: 42,
      damage: 18,
      armor: 0.12,
    },
    mind: {
      aggression: 0.72,
      patience: 1.15,
      courage: 0.8,
      erratic: 0.15,
      territorial: 0.9,
      fleeAt: 0.12,
      attacks: [ATTACK.DIVE_FIRE, ATTACK.DIVE_FIRE, ATTACK.TAIL_SWEEP],
      voice: { roar: 90, breath: 60 },
    },
    lines: {
      idle: "Ashwrought holds the ash ceiling.",
      spot: "Spotted. Ashwrought banks toward the ridge.",
      attack: "Dive-fire incoming. Break the cone.",
      pain: "The tyrant recoils — molten plates split.",
      flee: "Ashwrought climbs out of range.",
      dead: "Ashwrought falls. The ridge goes quiet.",
    },
  },

  cinderwyrm: {
    id: "cinderwyrm",
    name: "Cinderwyrm",
    epithet: "Forge-Hot Harrier",
    tier: 2,
    bounty: 350,
    codex:
      "Runs at forge temperature and never stops moving. Fast, reckless strafing passes with almost no wind-up — the hardest silhouette to lead, but thin-skinned.",
    build: {
      scale: 5.6,
      neck: 1.15,
      tailSegments: 6,
      horns: 4,
      hornLength: 0.45,
      spikes: true,
      wingSpan: 1.25,
      bodyGirth: 0.72,
      headSize: 0.85,
    },
    look: {
      pack: "scales_cinder",
      scaleRepeat: [2.4, 1.7],
      emissive: [1.4, 0.35, 0.05],
      emissiveBase: 0.4,
      eye: 0xffd070,
      glow: 0xff8420,
      glowIntensity: 17,
      metalness: 0.14,
      roughness: 0.36,
      wingTint: 0xffb08a,
    },
    stats: {
      hp: 620,
      flySpeed: 38,
      diveSpeed: 54,
      turnRate: 5.6,
      patrolRadius: 40,
      patrolHeight: 30,
      spotRange: 170,
      attackRange: 52,
      damage: 12,
      armor: 0.0,
    },
    mind: {
      aggression: 0.95,
      patience: 0.35,
      courage: 0.95,
      erratic: 0.7,
      territorial: 0.3,
      fleeAt: 0.0,
      attacks: [ATTACK.STRAFE_RUN, ATTACK.STRAFE_RUN, ATTACK.DIVE_FIRE],
      voice: { roar: 150, breath: 110 },
    },
    lines: {
      idle: "A Cinderwyrm burns a fast circuit overhead.",
      spot: "It saw you first. Cinderwyrm is already turning in.",
      attack: "Strafing run — it will not slow down.",
      pain: "Cinderwyrm shrieks and rolls off the line.",
      flee: "It refuses to disengage.",
      dead: "The Cinderwyrm goes dark mid-air.",
    },
  },

  basalt_tyrant: {
    id: "basalt_tyrant",
    name: "Basalt Tyrant",
    epithet: "Walking Siege",
    tier: 3,
    bounty: 900,
    codex:
      "Armored in cooled columnar rock. Too heavy for dive attacks, so it hovers at distance and lobs lava mortars, then lands to shake the ridge apart. Bolts glance off everything but the skull.",
    build: {
      scale: 12.5,
      neck: 0.78,
      tailSegments: 4,
      horns: 6,
      hornLength: 0.85,
      spikes: true,
      wingSpan: 0.82,
      bodyGirth: 1.5,
      headSize: 1.25,
    },
    look: {
      pack: "scales_basalt",
      scaleRepeat: [2.6, 1.8],
      emissive: [0.9, 0.14, 0.02],
      emissiveBase: 0.45,
      eye: 0xff6a10,
      glow: 0xff3a08,
      glowIntensity: 14,
      metalness: 0.06,
      roughness: 0.85,
      wingTint: 0x9a9a9a,
    },
    stats: {
      hp: 2600,
      flySpeed: 12,
      diveSpeed: 18,
      turnRate: 1.5,
      patrolRadius: 16,
      patrolHeight: 30,
      spotRange: 120,
      attackRange: 70,
      damage: 26,
      armor: 0.55,
    },
    mind: {
      aggression: 0.55,
      patience: 2.4,
      courage: 1.0,
      erratic: 0.05,
      territorial: 1.0,
      fleeAt: 0.0,
      attacks: [ATTACK.LAVA_MORTAR, ATTACK.LAVA_MORTAR, ATTACK.HOVER_BARRAGE, ATTACK.TAIL_SWEEP],
      voice: { roar: 52, breath: 40 },
    },
    lines: {
      idle: "Something very heavy is circling low.",
      spot: "The Basalt Tyrant has your range.",
      attack: "Mortar arc — move, do not backpedal.",
      pain: "Plates crack. Most of that bolt went nowhere.",
      flee: "It does not retreat.",
      dead: "The Tyrant drops like a collapsing cliff.",
    },
  },

  emberkin: {
    id: "emberkin",
    name: "Emberkin",
    epithet: "Carrion Scavenger",
    tier: 1,
    bounty: 120,
    codex:
      "Half-grown and cowardly. Circles wide, snatches at you only when your weapon is empty, and bolts for the ash column the moment it is hurt. Hunts in loose pairs.",
    build: {
      scale: 3.4,
      neck: 1.3,
      tailSegments: 6,
      horns: 2,
      hornLength: 0.3,
      spikes: false,
      wingSpan: 1.15,
      bodyGirth: 0.6,
      headSize: 0.8,
    },
    look: {
      pack: "scales_ember",
      scaleRepeat: [2.8, 2.0],
      emissive: [0.5, 0.16, 0.03],
      emissiveBase: 0.3,
      eye: 0xffc040,
      glow: 0xd07020,
      glowIntensity: 6,
      metalness: 0.6,
      roughness: 0.48,
      wingTint: 0xc79a6a,
    },
    stats: {
      hp: 240,
      flySpeed: 30,
      diveSpeed: 36,
      turnRate: 6.0,
      patrolRadius: 34,
      patrolHeight: 22,
      spotRange: 110,
      attackRange: 26,
      damage: 7,
      armor: 0.0,
    },
    mind: {
      aggression: 0.28,
      patience: 0.6,
      courage: 0.2,
      erratic: 0.55,
      territorial: 0.1,
      fleeAt: 0.55,
      opportunist: true,
      attacks: [ATTACK.AMBUSH_LUNGE, ATTACK.STRAFE_RUN],
      voice: { roar: 220, breath: 170 },
    },
    lines: {
      idle: "Emberkin keep their distance, watching.",
      spot: "An Emberkin is sizing you up.",
      attack: "It darts in while you are dry.",
      pain: "The scavenger screams and breaks away.",
      flee: "Emberkin flees for the ash column.",
      dead: "The scavenger tumbles into the rocks.",
    },
  },

  rustwing: {
    id: "rustwing",
    name: "Rustwing",
    epithet: "Pack Hunter",
    tier: 2,
    bounty: 420,
    codex:
      "Cold-blooded and never alone. A lone Rustwing keeps its distance and looks almost tame; every packmate that commits to the hunt makes the rest of them braver, and three of them will run you off the ridge. Kill one and the survivors lose their nerve.",
    build: {
      scale: 4.6,
      neck: 1.2,
      tailSegments: 6,
      horns: 3,
      hornLength: 0.4,
      spikes: true,
      wingSpan: 1.35,
      bodyGirth: 0.65,
      headSize: 0.85,
    },
    look: {
      pack: "scales_kin",
      scaleRepeat: [2.6, 1.8],
      emissive: [0.62, 0.2, 0.07],
      emissiveBase: 0.35,
      eye: 0xffd9a0,
      glow: 0x8a5a3a,
      glowIntensity: 4,
      metalness: 0.5,
      roughness: 0.62,
      wingTint: 0x9aa4ad,
    },
    stats: {
      hp: 380,
      flySpeed: 34,
      diveSpeed: 46,
      turnRate: 5.2,
      patrolRadius: 44,
      patrolHeight: 24,
      spotRange: 160,
      attackRange: 30,
      damage: 11,
      armor: 0.05,
    },
    mind: {
      aggression: 0.35,
      patience: 0.8,
      courage: 0.45,
      erratic: 0.4,
      territorial: 0.2,
      fleeAt: 0.3,
      // Each packmate already in the fight adds this much live aggression.
      packMinded: 0.2,
      attacks: [ATTACK.STRAFE_RUN, ATTACK.AMBUSH_LUNGE, ATTACK.TAIL_SWEEP],
      voice: { roar: 170, breath: 140 },
    },
    lines: {
      idle: "Rustwings circle wide, waiting for each other.",
      spot: "One Rustwing peels off. The others are watching it.",
      attack: "The pack commits together — do not let them surround you.",
      pain: "It screeches, and the whole pack answers.",
      flee: "Without its pack the Rustwing loses its nerve.",
      dead: "A Rustwing drops. The rest hesitate.",
    },
  },

  pale_stalker: {
    id: "pale_stalker",
    name: "Pale Stalker",
    epithet: "Silent Ambusher",
    tier: 3,
    bounty: 750,
    codex:
      "Ash-blind hunter that stops flapping to fall silent. It will shadow you for a long time without attacking, then close the distance in one lunge from behind cover.",
    build: {
      scale: 7.0,
      neck: 1.25,
      tailSegments: 7,
      horns: 4,
      hornLength: 0.95,
      spikes: true,
      wingSpan: 1.1,
      bodyGirth: 0.8,
      headSize: 0.95,
    },
    look: {
      pack: "scales_pale",
      scaleRepeat: [1.3, 0.9],
      emissive: [0.18, 0.22, 0.3],
      emissiveBase: 0.22,
      eye: 0x9fe0ff,
      glow: 0x6a8ab0,
      glowIntensity: 5,
      metalness: 0.05,
      roughness: 0.72,
      wingTint: 0xd8d2c6,
    },
    stats: {
      hp: 900,
      flySpeed: 26,
      diveSpeed: 62,
      turnRate: 4.4,
      patrolRadius: 52,
      patrolHeight: 42,
      spotRange: 190,
      attackRange: 34,
      damage: 30,
      armor: 0.18,
    },
    mind: {
      aggression: 0.62,
      patience: 3.2,
      courage: 0.7,
      erratic: 0.2,
      territorial: 0.4,
      fleeAt: 0.2,
      stalker: true,
      attacks: [ATTACK.AMBUSH_LUNGE, ATTACK.AMBUSH_LUNGE, ATTACK.DIVE_FIRE],
      voice: { roar: 70, breath: 300 },
    },
    lines: {
      idle: "Something pale is keeping pace with you in the ash.",
      spot: "It knows you saw it. It stops flapping.",
      attack: "Lunge — it came in silent.",
      pain: "The Stalker hisses and fades back into the ash.",
      flee: "It withdraws to stalk again.",
      dead: "The Pale Stalker folds up and drops.",
    },
  },

  sulfurmaw: {
    id: "sulfurmaw",
    name: "Sulfurmaw",
    epithet: "Fumarole Brood",
    tier: 2,
    bounty: 480,
    codex:
      "Nests in sulfur vents. Instead of fire it sprays a caustic aerosol that hangs in the air and keeps burning after the pass, so its favorite tactic is to fence you into your own cover.",
    build: {
      scale: 6.4,
      neck: 1.4,
      tailSegments: 5,
      horns: 2,
      hornLength: 0.55,
      spikes: false,
      wingSpan: 0.95,
      bodyGirth: 0.95,
      headSize: 1.1,
    },
    look: {
      pack: "scales_sulfur",
      scaleRepeat: [2.4, 1.7],
      emissive: [0.5, 0.95, 0.1],
      emissiveBase: 0.5,
      eye: 0xd8ff40,
      glow: 0xaadd20,
      glowIntensity: 12,
      metalness: 0.1,
      roughness: 0.38,
      wingTint: 0xb5c07a,
    },
    stats: {
      hp: 1000,
      flySpeed: 20,
      diveSpeed: 30,
      turnRate: 2.8,
      patrolRadius: 26,
      patrolHeight: 26,
      spotRange: 130,
      attackRange: 40,
      damage: 14,
      armor: 0.1,
    },
    mind: {
      aggression: 0.6,
      patience: 1.6,
      courage: 0.75,
      erratic: 0.25,
      territorial: 0.7,
      fleeAt: 0.15,
      breath: "venom",
      attacks: [ATTACK.VENOM_SPRAY, ATTACK.VENOM_SPRAY, ATTACK.HOVER_BARRAGE],
      voice: { roar: 110, breath: 220 },
    },
    lines: {
      idle: "A Sulfurmaw drifts over the vents.",
      spot: "Sulfurmaw turns. Watch the wind.",
      attack: "Caustic spray — the cloud lingers, keep moving.",
      pain: "It gags and spits bile off-target.",
      flee: "Sulfurmaw pulls back over the vents.",
      dead: "The Sulfurmaw drops, venting steam.",
    },
  },
};

export const SPECIES_ORDER = [
  "emberkin",
  "cinderwyrm",
  "ashwrought",
  "rustwing",
  "sulfurmaw",
  "pale_stalker",
  "basalt_tyrant",
];

/** Texture packs that are not needed until a species actually spawns. */
export const LAZY_PACKS = [
  "scales_cinder",
  "scales_basalt",
  "scales_ember",
  "scales_pale",
  "scales_sulfur",
  "scales_kin",
];

export function speciesPack(id) {
  return SPECIES[id].look.pack;
}
